name: pixiv_func_android
description: Pixiv Android 客户端

version: 0.2.1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #国际化
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_annotation: ^4.1.0
  provider: ^6.0.0
  dio: ^4.0.0
  crypto: ^3.0.1
  #数据持久化
  shared_preferences: ^2.0.0
  extended_image: ^4.1.0
  cached_network_image: ^3.1.0
  intl: ^0.17.0
  #下拉刷新上拉加载
  pull_to_refresh: ^2.0.0
  #瀑布流
  flutter_staggered_grid_view: ^0.4.0
  #日志
  logger: ^1.0.0
  #解析html
  html: ^0.15.0
  #申请权限
  permission_handler: ^8.1.4+2
  image_picker: ^0.8.4
dev_dependencies:
  json_serializable: ^5.0.0
  build_runner: ^2.1.1
flutter:
  uses-material-design: true
  assets:
    - assets/stamps/
    - assets/xiaocao.png
    - assets/kotlin-logo.png
    - assets/dart-logo.png
