name: pixiv_xiaocao_android
description: Pixiv 安卓客户端

version: 0.1.8

environment:
  sdk: ">=2.12.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_annotation: ^4.0.1
  dio: ^4.0.0
  url_launcher: ^6.0.4
  package_info: ^2.0.0
  provider: ^5.0.0
  extended_image: ^4.0.1
  cached_network_image: ^3.0.0
  flutter_staggered_grid_view: ^0.4.0
  oktoast: ^3.0.0
  permission_handler: ^7.1.0
  image_picker: ^0.7.5+3
  pull_to_refresh: ^2.0.0
  html: ^0.15.0



flutter:
  uses-material-design: true
  assets:
    - assets/
